In [1]:
import numpy as np

1. Create 1D and 2D arrays

In [2]:
python_list=[2,4,6,8]
array_1D=np.array(python_list)
array_2D=np.array([
    [1,2,3],
    [4,5,6],
])
print(array_1D)
print(array_2D)

[2 4 6 8]
[[1 2 3]
 [4 5 6]]


2. Check basic properties

In [5]:
x=np.array([
    [1,2,3],
    [4,5,6],
])
print("Shape of x:",x.shape)
print("Dimension of x:",x.ndim)
print("Type of x:",x.dtype)

Shape of x: (2, 3)
Dimension of x: 2
Type of x: int64


3. Zeros and ones

In [11]:
zeros=np.zeros((3,3))
ones=np.ones((2,4))
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. arange vs linspace

In [12]:
ar1=np.arange(0,10,2)
ar2=np.linspace(0,1,5)
print(ar1)
print(ar2)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
